# Site settings
title: Development the way it should be
email: jlordiales@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Random thoughts and learnings from an agile developer. Mostly a
  self-learning journey, hopefully helping other people along the
  way.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jlordiales.github.io" # the base hostname & protocol for your site
twitter_username: jlordiales
github_username:  jlordiales

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title
